version: '3'

services:
  node:
      build:
        context: .
        dockerfile: ./Dockerfiles/DockerfileDev
      links:
        - mongodb
      volumes:
        - node_modules:/app/node_modules
        - ./yarn.lock:/app/yarn.lock
        - ./package.json:/app/package.json
        - ./src:/app/src
      container_name: videx-db-migration-node-dev
      command: yarn run dev

  mongodb:
      image: mongo:3.6.6
      volumes:
        - XXX:/data/db
      ports:
        - "27017:27017"
      container_name: videx-db-migration-mongodb-dev

volumes:
  node_modules:
    driver: local
